### ISSUE TITLE
Read file

### ISSUE THREAD

**Issue by andreock** [pierremacedo/nativescript-android-fs#1]
Hi, with this library I can read a file?

**Comment by pierreamgabriel** [comment]
> Hi, with this library I can read a file?

Generally speaking yes, but can you give more details on what you need?

**Comment by andreock** [comment]
I Need read a file Whitch Is written with storage.create but i don't find any function in readme.

**Comment by pierreamgabriel** [comment]
> I Need read a file Whitch Is written with storage.create but i don't find any function in readme.

I added a new function called ```storage.read```. It returns a string with the content of a text file. Update the plugin by running ```npm install nativescript-android-fs``` and go to readme for instructions.

**Comment by andreock** [comment]
Thank you!
