### ISSUE TITLE
  ERROR TypeError: storage.save is not a function

### ISSUE THREAD

**Issue by AAlex-11** [pierremacedo/nativescript-android-fs#2]
ns plugin add nativescript-android-fs
          let storage = require("nativescript-android-fs");
          storage.save("/Documents", filename);

![MyVault-06042024_012045_1](https://github.com/pierreamgabriel/nativescript-android-fs/assets/138773344/08940cd7-c49d-4e77-a31a-199ccfc03f7d)

![MyVault-06042024_012416_1](https://github.com/pierreamgabriel/nativescript-android-fs/assets/138773344/7eba189a-89a7-403f-abee-4d699b4b0e73)

working with storage.default.save

**Comment by pierreamgabriel** [comment]
@AAlex-11 Hi there. I have no way to test and fix this, as I don't use NS anymore. Actually, if you're working on a personal project, I suggest you to go with React Native because NS has no future. But you're free to clone this repo and add TS to this project. Sorry I can't help you.

**Comment by AAlex-11** [comment]
yes, I'm understand. BTW, storage.default.save always return false.

**Comment by AAlex-11** [comment]
and yes, I'm agree that NS has no future. If you want to use programming to Windows, you must use Microsoft environment, if you want to write to Google phone, you must use Google Android Studio, Any so named "cross platform" backdoor don't working, because that backdoor created a couple of cool private programmers as enthusiasts and volunteers, this is not workable schema to crack huge Google Android environment.

**Comment by pierreamgabriel** [comment]
If you share you're NS version and Android version you're testing it, maybe I can take a look later.

**Comment by AAlex-11** [comment]
all Angular and NS version is just fresh. last as possible, Android emulator API 30 Android 11.
perform method
 
         storage.default.save("/Documents", filename);

produced this error

![IMG_20240604_143836_1](https://github.com/pierreamgabriel/nativescript-android-fs/assets/138773344/3b34f174-eb3f-4512-b17b-3cc71dadefce)

**Comment by pierreamgabriel** [comment]
@AAlex-11 I just tested it with the latest NS 8.7.2 and Android 14, and it's working fine. You just need to use `import storage from 'nativescript-android-fs';`, instead of using `require`.

Besides, storage.default.save doesn't exist. The correct syntax is storage.save, AND it must have a file to save from /data/user/0/com.package.name/files to external storage.
